# Generated by Django 4.1.7 on 2023-02-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertie.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=150)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertie.arrendatario')),
            ],
        ),
    ]
