# Generated by Django 4.1.7 on 2023-02-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertie', '0002_arrendatario_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='rooms_available',
        ),
    ]
