# Generated by Django 4.1.7 on 2023-02-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertie', '0003_remove_departamento_rooms_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='emmited_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='expired_date',
            field=models.DateField(null=True),
        ),
    ]
