# Generated by Django 4.1.7 on 2023-03-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertie', '0005_rename_type_recibo_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='departamento',
            new_name='casa',
        ),
    ]
